version: '3'
services:
  timeservice:
    image: "iot:timeservice"
    ports:
      - "8081:8080"
    build:
      context: ./timeservice
      args:
        JAR_FILE: timeservice-swarm.jar
        PORT_NUMBER: 8080
  weatherservice:
    image: "iot:weatherservice"
    ports:
      - "8082:8080"
    build:
      context: ./weatherservice
      args:
        JAR_FILE: weatherservice-swarm.jar
        PORT_NUMBER: 8080